# Base configs
baseurl: "https://art.limamedeiros.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Art by Vanessa Medeiros"
subtitle: ""
author: "Vanessa Medeiros"
header:
 title: "Art"
 subtitle: "by Vanessa Medeiros"
footer:
 name: ""
 bio: ""
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  linkedin: "https://in.linkedin.com/in/limamedeiros"
  github: "https://www.github.com/limamedeiros"
